	section	code
	xdef	mult320

; Shared chunky row offsets, generated by the assembler (no startup work).
; 256 long entries also cover off-display rows in original HUD save-under
; operations. Callers must validate their surface bounds before indexing.
	cnop	0,4
mult320:
mult320_row	set	0
	rept	256
	dc.l	mult320_row*320
mult320_row	set	mult320_row+1
	endr
